// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTtieFhmNJc-Aq32qS5LFwH3N214P4GnA',
    appId: '1:792645958650:web:1ee92feedbc4f3b3a38243',
    messagingSenderId: '792645958650',
    projectId: 'thefoodtranslator-28cc2',
    authDomain: 'thefoodtranslator-28cc2.firebaseapp.com',
    storageBucket: 'thefoodtranslator-28cc2.firebasestorage.app',
    measurementId: 'G-GFFFWHDM7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5w-ejJRabzkSQDg1CNNNHviLPa6J1PYI',
    appId: '1:792645958650:android:b81a46867de84faaa38243',
    messagingSenderId: '792645958650',
    projectId: 'thefoodtranslator-28cc2',
    storageBucket: 'thefoodtranslator-28cc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoPTza65cIZpbJUJCT1uKF21CT6z0hr-4',
    appId: '1:792645958650:ios:057c7a5af81bc693a38243',
    messagingSenderId: '792645958650',
    projectId: 'thefoodtranslator-28cc2',
    storageBucket: 'thefoodtranslator-28cc2.firebasestorage.app',
    iosBundleId: 'com.example.theFoodTranslatorV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoPTza65cIZpbJUJCT1uKF21CT6z0hr-4',
    appId: '1:792645958650:ios:057c7a5af81bc693a38243',
    messagingSenderId: '792645958650',
    projectId: 'thefoodtranslator-28cc2',
    storageBucket: 'thefoodtranslator-28cc2.firebasestorage.app',
    iosBundleId: 'com.example.theFoodTranslatorV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTtieFhmNJc-Aq32qS5LFwH3N214P4GnA',
    appId: '1:792645958650:web:704212dc2727b4dba38243',
    messagingSenderId: '792645958650',
    projectId: 'thefoodtranslator-28cc2',
    authDomain: 'thefoodtranslator-28cc2.firebaseapp.com',
    storageBucket: 'thefoodtranslator-28cc2.firebasestorage.app',
    measurementId: 'G-LSY5HZ8Q7L',
  );
}
